#!/bin/bash

commitMessage=$1

function getCoauthor {
  signiture=$(git log --no-merges -1 --author "$1" --format='%an <%ae>' 2>/dev/null)
  echo "Co-authored-by: $signiture"
}

coworkers=$(git config --get-all coworking.coauthor)
if [ $? -eq 0 ]
then
  echo "" >> $commitMessage
  for coworker in "$coworkers"
  do
    echo "$(getCoauthor $coworker)" >> $commitMessage
  done
fi
