#!/usr/bin/env node

const fs = require('fs')
const path = require('path')
const {execSync} = require('child_process')

const cwd = process.cwd()
const coworkingFile = path.resolve(cwd, ".coauthoring-with")
const commitMessage = process.argv[2]

if (fs.existsSync(coworkingFile)) {
  let message = ['']
  for (const username of fs.readFileSync(coworkingFile, 'utf8').split('\n')) {
    message.push(execSync(`git get-coauthor ${username}`))
  }
  fs.appendFileSync(commitMessage, message.join('\n'))
}
